# Site settings


title: Montana News Archive
email: mtnewsarchive@gmail.com
description: >
  This site is the documentation website for Montana News Archive,
  a software project designed to give broadcasters a pathway
  to digitize and catalogue their historical archive materials. 
url: "http://mtnewsarchive.net"
github_organization: PronghornDigital
github_link: https://github.com/PronghornDigital/Montana-News-Archive
#Build settings
markdown: kramdown

collections:
  docs:
    output: true
    permalink: /docs/
    title: Documentation
